# Change the design of the shop here
# You are able to choose between:
# Normal
# HyPixel
# HiveMC
# GommeHD
# Rewinside
# Minesucht
# BergwerkLABS
# HyPixelV2

# DO NOT change this
file-version: 1

gui:
  height: 1
  title: 'Choose Shop Layout'
  selected-layout: '&a&lSELECTED'

# How the layouts are displayed in the GUI
# If you have a custom shop layout, simply add it to this list
layouts:
  Normal:
    display-name: 'Normal'
    material: 'POTATO'
    slot: 1
    lore:
      - "Default MBedwars Layout"

  Hypixel:
    display-name: 'Hypixel V1'
    material: 'POTATO'
    slot: 2
    lore:
      - "Old Hypixel Layout"

  HiveMC:
    display-name: 'HiveMC'
    Material: 'POTATO'
    slot: 3
    lore:
      - "HiveMC's Layout"

  GommeHD:
    display-name: 'GommeHD'
    material: 'POTATO'
    slot: 4
    lore:
      - "GommeHD Shop Layout"

  Rewinside:
    display-name: 'Rewinside'
    material: 'POTATO'
    slot: 5
    lore:
      - "Rewinside Shop Layout"

  BergwerkLABS:
    display-name: 'BergwerkLABS'
    material: 'POTATO'
    slot: 6
    lore:
      - 'BergwerkLABS Shop Layout'

  HyPixel_V2:
    display-name: 'Hypixel V2'
    material: 'POTATO'
    slot: 7
    lore:
      - "Hypixel's Current Shop Layout"

  Minesucht:
    display-name: 'Minesucht'
    material: 'POTATO'
    slot: 8
    lore:
      - "Minesucht shop layout"