website: http://marcely.de
version: 2.0.0
name: SelectShopDesignAddon
authors: [Marcely1199, MetallicGoat]
main: de.marcely.bedwars.selectshopdesign.SelectShopDesignPlugin
api-version: 1.13
description: This is an add-on for Marcely's Bedwars
depend: [MBedwars]